### ISSUE TITLE
Telegram group link is incorrect?

### ISSUE THREAD

**Issue by shesek** [bit-matrix/script-wiz-ui#20]
https://t.me/scriptwizard appears to be a personal profile and not a chat group.

Incredible work btw :) I'm finding scriptwiz super useful, especially for experimenting with Liquid's new covenants opcodes. Thank you for making this!

**Comment by PenguenUmut** [comment]
Yes, there is a problem with the link, thanks for your feedback. @brqgoo can fix it asap. 

Also thank you for your motivating comments 🥰

**Comment by afarukcali** [comment]
Hi @shesek , we changed telegram url. Thank you so much your other issues.We are focusing new features for ScriptWiz. After that , we will fix the issues. New telegram url is : https://t.me/+bEiJnTeu-mA1ODRk
